// <auto-generated />
using FactoryPatternDemo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryPatternDemo.Migrations
{
    [DbContext(typeof(FactoryDBContext))]
    [Migration("20231228154911_initA")]
    partial class initA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FactoryPatternDemo.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("AnimalType").HasValue("Animal");
                });

            modelBuilder.Entity("FactoryPatternDemo.Models.Elephant", b =>
                {
                    b.HasBaseType("FactoryPatternDemo.Models.Animal");

                    b.HasDiscriminator().HasValue("Elephant");
                });

            modelBuilder.Entity("FactoryPatternDemo.Models.Lion", b =>
                {
                    b.HasBaseType("FactoryPatternDemo.Models.Animal");

                    b.HasDiscriminator().HasValue("Lion");
                });
#pragma warning restore 612, 618
        }
    }
}
